ARG PYTHON_VERSION=3

# --------------------------------------------- base1
FROM alt:p11 AS base1

RUN apt-get update && apt-get install -y \
    sudo \
    curl \
    ca-certificates \
    openssh-server \
    openssh-clients \
    sshpass \
    time \
    su \
    git \
    procps \
    && apt-get clean

# --------------------------------------------- base2_with_python-3
FROM base1 AS base2_with_python-3

RUN apt-get update && apt-get install -y \
    python3 \
    python3-dev \
    && apt-get clean

ENV PYTHON_VERSION=3

# --------------------------------------------- final
FROM base2_with_python-${PYTHON_VERSION} AS final

EXPOSE 22
RUN ssh-keygen -A

RUN adduser test -G wheel

# It enables execution of "sudo service ssh start" without password
RUN echo "test ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers

#
# Altlinux 10 and 11 too slowly create a new SSH connection (x6).
#
# AI: SPEED UP SSH 6 TIMES (REMOVE REVERSE DNS LOOKUP TIMEOUTS)
#
RUN echo "UseDNS no" >> /etc/openssh/sshd_config

COPY --chown=test:test . /home/test/testgres
WORKDIR /home/test/testgres

ENV LANG=C.UTF-8

RUN chmod 700 /home/test/ && \
    mkdir -p /home/test/.ssh && \
    chown -R test:test /home/test/.ssh

USER test

ENTRYPOINT sh -c " \
set -eux; \
echo HELLO FROM ENTRYPOINT; \
echo HOME DIR IS [`realpath ~/`]; \
sudo /usr/sbin/sshd; \
ssh-keyscan -H localhost >> ~/.ssh/known_hosts; \
ssh-keyscan -H 127.0.0.1 >> ~/.ssh/known_hosts; \
ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -N ''; \
cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys; \
chmod 600 ~/.ssh/authorized_keys; \
ls -la ~/.ssh/; \
TEST_FILTER=\"\" bash ./run_tests3.sh;"
