ARG PYTHON_VERSION=3.12

# --------------------------------------------- base1
FROM python:${PYTHON_VERSION}-alpine AS base1

RUN apk add --no-cache \
    coreutils \
    bash \
    mc \
    procps \
    openssh \
    sshpass \
    sudo \
    git

# --------------------------------------------- base2
FROM base1 AS base2

RUN apk add --no-cache \
    python3-dev \
    build-base\
    musl-dev \
    linux-headers

# --------------------------------------------- final
FROM base2 AS final

RUN adduser -D test && addgroup -S sudo && adduser test sudo

EXPOSE 22
RUN ssh-keygen -A

COPY --chown=test:test . /home/test/testgres
WORKDIR /home/test/testgres

# It allows to use sudo without password
RUN echo "test ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers

# THIS CMD IS NEEDED TO CONNECT THROUGH SSH WITHOUT PASSWORD
RUN sh -c "echo "test:*" | chpasswd -e"

USER test

# THIS CMD IS NEEDED TO CONNECT THROUGH SSH WITHOUT PASSWORD
RUN chmod 700 ~/

RUN mkdir -p ~/.ssh
#RUN chmod 700 ~/.ssh

ENTRYPOINT sh -c " \
set -eux; \
echo HELLO FROM ENTRYPOINT; \
echo HOME DIR IS [`realpath ~/`]; \
echo WORK DIR IS [$(pwd)]; \
ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -N ''; \
cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys; \
chmod 600 ~/.ssh/authorized_keys; \
ls -la ~/.ssh/; \
sudo /usr/sbin/sshd; \
ssh-keyscan -H localhost >> ~/.ssh/known_hosts; \
ssh-keyscan -H 127.0.0.1 >> ~/.ssh/known_hosts; \
bash run_tests3.sh;"
