ARG PYTHON_VERSION=3

# --------------------------------------------- base1
FROM alt:p11 AS base1

RUN apt-get update && apt-get install -y \
    sudo \
    curl \
    ca-certificates \
    openssh-server \
    openssh-clients \
    sshpass \
    time \
    su \
    git \
    procps \
    && apt-get clean

# --------------------------------------------- base2_with_python-3
FROM base1 AS base2_with_python-3

RUN apt-get update && apt-get install -y \
    python3 \
    python3-dev \
    && apt-get clean

ENV PYTHON_VERSION=3

# --------------------------------------------- final
FROM base2_with_python-${PYTHON_VERSION} AS final

EXPOSE 22
RUN ssh-keygen -A

RUN adduser test -G wheel

# It enables execution of "sudo service ssh start" without password
RUN echo "test ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers

#
# Altlinux 10 and 11 too slowly create a new SSH connection (x6).
#
# AI: SPEED UP SSH 6 TIMES (REMOVE REVERSE DNS LOOKUP TIMEOUTS)
#
RUN echo "UseDNS no" >> /etc/openssh/sshd_config

COPY --chown=test:test . /home/test/testgres
WORKDIR /home/test/testgres

ENV LANG=C.UTF-8

RUN chmod 700 /home/test/ && \
    mkdir -p /home/test/.ssh && \
    chown -R test:test /home/test/.ssh

#
# \"$@\"
#   - quote is important!
#   - "DUMMY-DUMMY-DUMMY" will be ignored. Do not ask me "why?". AXEZ.
#
ENTRYPOINT ["sh", "-c", " \
    set -eux; \
    echo 'SYSTEM START: PREPARING SSH'; \
    /usr/sbin/sshd; \
    ls -la /home/test/.ssh/; \
    \"$@\" \
", "DUMMY-DUMMY-DUMMY"]

# Run tests by default (master machine role)
CMD ["bash", "-c", " \
set -eux; \
echo \"HOME DIR IS [`realpath ~/`]\"; \
echo \"WORK DIR IS [$(pwd)]\"; \
if [ ! -f /home/test/.ssh/id_rsa ]; then \
    su -c \"ssh-keygen -t rsa -f /home/test/.ssh/id_rsa -q -N ''\" test; \
    su -c \"cat /home/test/.ssh/id_rsa.pub >> /home/test/.ssh/authorized_keys\" test; \
    chmod 600 /home/test/.ssh/authorized_keys; \
fi; \
ls -la /home/test/.ssh/; \
su -c \"ssh-keyscan -H localhost >> /home/test/.ssh/known_hosts\" test; \
su -c \"ssh-keyscan -H 127.0.0.1 >> /home/test/.ssh/known_hosts\" test; \
if [ -n \"${TEST_CFG__REMOTE_HOST:-}\" ]; then \
    su -c \"ssh-keyscan -H ${TEST_CFG__REMOTE_HOST} >> /home/test/.ssh/known_hosts\" test; \
fi; \
if [ -n \"${TEST_CFG__REMOTE_SSH_KEY:-}\" ]; then \
    cp \"${TEST_CFG__REMOTE_SSH_KEY}\" \"${TEST_CFG__REMOTE_SSH_KEY}_ci\"; \
    export TEST_CFG__REMOTE_SSH_KEY=\"${TEST_CFG__REMOTE_SSH_KEY}_ci\"; \
    chown test:test \"${TEST_CFG__REMOTE_SSH_KEY}\"; \
    chmod 600 \"${TEST_CFG__REMOTE_SSH_KEY}\"; \
    ls -la /home/test/.ssh/; \
fi; \
ls -la ./; \
# AUTOMATIC TRANSFER: Save all TEST_CFG__xxx variables to a temporary file \
(env | grep '^TEST_CFG__' | sed 's/^/export /' || echo '') > ./test_cfg_env.sh; \
chown test:test ./test_cfg_env.sh; \
cat ./test_cfg_env.sh; \
# Run su -, pull in the file with variables and start the tests \
su - test -c \"cd /home/test/testgres && source ./test_cfg_env.sh && bash ./run_tests3.sh\"; \
"]
